theme: jekyll-theme-primer
title: MARGO & TREVOR
navbar-links:
    HOME: "margo-trevor.com"
    #SCHEDULE: "schedule"
    TRAVEL: "travel"
    REGISTRY: "registry"
    #WEDDING PARTY: "weddingparty"
    #PHOTOS: "photos"
    THINGS TO DO: "thingstodo"
    #FAQS: "faqs"
