theme: jekyll-theme-primer
title: MARGO & TREVOR
navbar-links:
    HOME: "index.md"
    #SCHEDULE: "schedule"
    TRAVEL: "travel.md"
    REGISTRY: "registry.md"
    #WEDDING PARTY: "weddingparty"
    PHOTOS: "photos"
    THINGS TO DO: "thingstodo.md"
    #FAQS: "faqs"
